version: "3.5"

services:
  bg-parent1:
    image: beer-garden:local
    container_name: bg-parent1
    hostname: bg-parent1
    stdin_open: true
    tty: true
    command:
      [
        "-c",
        "source /home/brewmeister/venv/bin/activate && /opt/scripts/move_sitecustomize.sh && python bin/app.py -c ../conf/bg-parent1.yaml -l ../conf/app-logging.yaml",
      ]
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONBREAKPOINT: remote_pdb.set_trace
      REMOTE_PDB_HOST: 0.0.0.0
      REMOTE_PDB_PORT: 3333
    networks:
      - bg-network
    ports:
      - "2337:2337"
      - "2338:2338"
      - "3333:3333"
    volumes:
      - $PROJECT_HOME/beer-garden/src/app:/home/brewmeister/beer-garden/app
      - $PROJECT_HOME/beer-garden-plugins:/home/brewmeister/beer-garden/plugins
      - $PROJECT_HOME:/opt/libraries
      - $PROJECT_HOME/dev-utils/beer-garden/conf:/home/brewmeister/beer-garden/conf
      - $PROJECT_HOME/dev-utils/docker-scripts/move_sitecustomize.sh:/opt/scripts/move_sitecustomize.sh
      - $PROJECT_HOME/dev-utils/docker-scripts/sitecustomize.py:/opt/scripts/sitecustomize.py
      - $PROJECT_HOME/dev-utils/beer-garden/scripts/scratch.py:/opt/scratch.py
      - $PROJECT_HOME/dev-utils/beer-garden/conf/requirements.local.txt:/opt/requirements.local.txt
    depends_on:
      - mongodb
      - rabbitmq
      - activemq

  bg-child1:
    image: beer-garden:local
    container_name: bg-child1
    hostname: bg-child1
    stdin_open: true
    tty: true
    command:
      [
        "-c",
        "source /home/brewmeister/venv/bin/activate && /opt/scripts/move_sitecustomize.sh && python bin/app.py -c ../conf/bg-child1.yaml -l ../conf/app-logging.yaml",
      ]
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONBREAKPOINT: remote_pdb.set_trace
      REMOTE_PDB_HOST: 0.0.0.0
      REMOTE_PDB_PORT: 4444
    networks:
      - bg-network
    ports:
      - "2447:2447"
      - "2448:2448"
      - "4444:4444"
    volumes:
      - $PROJECT_HOME/beer-garden/src/app:/home/brewmeister/beer-garden/app
      - $PROJECT_HOME/beer-garden-plugins:/home/brewmeister/beer-garden/plugins
      - $PROJECT_HOME:/opt/libraries
      - $PROJECT_HOME/dev-utils/beer-garden/conf:/home/brewmeister/beer-garden/conf
      - $PROJECT_HOME/dev-utils/docker-scripts/move_sitecustomize.sh:/opt/scripts/move_sitecustomize.sh
      - $PROJECT_HOME/dev-utils/docker-scripts/sitecustomize.py:/opt/scripts/sitecustomize.py
      - $PROJECT_HOME/dev-utils/beer-garden/scripts/scratch.py:/opt/scratch.py
      - $PROJECT_HOME/dev-utils/beer-garden/conf/requirements.local.txt:/opt/requirements.local.txt
    depends_on:
      - mongodb
      - rabbitmq
      - activemq

  bg-child2:
    image: beer-garden:local
    container_name: bg-child2
    hostname: bg-child2
    stdin_open: true
    tty: true
    command:
      [
        "-c",
        "source /home/brewmeister/venv/bin/activate && /opt/scripts/move_sitecustomize.sh && python bin/app.py -c ../conf/bg-child2.yaml -l ../conf/app-logging.yaml",
      ]
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONBREAKPOINT: remote_pdb.set_trace
      REMOTE_PDB_HOST: 0.0.0.0
      REMOTE_PDB_PORT: 5555
    networks:
      - bg-network
    ports:
      - "2557:2557"
      - "2558:2558"
      - "5555:5555"
    volumes:
      - $PROJECT_HOME/beer-garden/src/app:/home/brewmeister/beer-garden/app
      - $PROJECT_HOME/beer-garden-plugins:/home/brewmeister/beer-garden/plugins
      - $PROJECT_HOME:/opt/libraries
      - $PROJECT_HOME/dev-utils/beer-garden/conf:/home/brewmeister/beer-garden/conf
      - $PROJECT_HOME/dev-utils/docker-scripts/move_sitecustomize.sh:/opt/scripts/move_sitecustomize.sh
      - $PROJECT_HOME/dev-utils/docker-scripts/sitecustomize.py:/opt/scripts/sitecustomize.py
      - $PROJECT_HOME/dev-utils/beer-garden/scripts/scratch.py:/opt/scratch.py
      - $PROJECT_HOME/dev-utils/beer-garden/conf/requirements.local.txt:/opt/requirements.local.txt
    depends_on:
      - mongodb
      - rabbitmq
      - activemq

  bg-child2-grandchild1:
    image: beer-garden:local
    container_name: bg-child2-grandchild1
    hostname: bg-child2-grandchild1
    stdin_open: true
    tty: true
    command:
      [
        "-c",
        "source /home/brewmeister/venv/bin/activate && /opt/scripts/move_sitecustomize.sh && python bin/app.py -c ../conf/bg-child2-grandchild1.yaml -l ../conf/app-logging.yaml",
      ]
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONBREAKPOINT: remote_pdb.set_trace
      REMOTE_PDB_HOST: 0.0.0.0
      REMOTE_PDB_PORT: 6666
    networks:
      - bg-network
    ports:
      - "2667:2667"
      - "2668:2668"
      - "6666:6666"
    volumes:
      - $PROJECT_HOME/beer-garden/src/app:/home/brewmeister/beer-garden/app
      - $PROJECT_HOME/beer-garden-plugins:/home/brewmeister/beer-garden/plugins
      - $PROJECT_HOME:/opt/libraries
      - $PROJECT_HOME/dev-utils/beer-garden/conf:/home/brewmeister/beer-garden/conf
      - $PROJECT_HOME/dev-utils/docker-scripts/move_sitecustomize.sh:/opt/scripts/move_sitecustomize.sh
      - $PROJECT_HOME/dev-utils/docker-scripts/sitecustomize.py:/opt/scripts/sitecustomize.py
      - $PROJECT_HOME/dev-utils/beer-garden/scripts/scratch.py:/opt/scratch.py
      - $PROJECT_HOME/dev-utils/beer-garden/conf/requirements.local.txt:/opt/requirements.local.txt
    depends_on:
      - mongodb
      - rabbitmq
      - activemq

  beer-garden-remote-plugin:
    image: beer-garden-remote-plugin:local
    container_name: beer-garden-remote-plugin
    stdin_open: true
    tty: true
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONBREAKPOINT: remote_pdb.set_trace
      REMOTE_PDB_HOST: 0.0.0.0
      REMOTE_PDB_PORT: 8888
    networks:
      - bg-network
    ports:
      - "8888:8888"
    volumes:
      - $PROJECT_HOME/remote-plugins:/home/brewmeister/beer-garden/plugins
      - $PROJECT_HOME:/opt/libraries
      - $PROJECT_HOME/dev-utils/docker-scripts/move_sitecustomize.sh:/opt/scripts/move_sitecustomize.sh
      - $PROJECT_HOME/dev-utils/docker-scripts/sitecustomize.py:/opt/scripts/sitecustomize.py
      - $PROJECT_HOME/dev-utils/beer-garden/conf/requirements.local.txt:/opt/requirements.local.txt

  bg-parent1-ui:
    image: beer-garden-ui:local
    container_name: bg-parent1-ui
    stdin_open: true
    tty: true
    environment:
      BEERGARDEN_HOST: beer-garden
      BEERGARDEN_PORT: 2337
    networks:
      - bg-network
    ports:
      - "8080:8080"
    volumes:
      - $PROJECT_HOME/beer-garden/src/ui:/home/brewmeister/beer-garden/ui
      - $PROJECT_HOME/dev-utils/beer-garden/conf/webpack.bg-parent1.js:/home/brewmeister/beer-garden/ui/webpack.dev-utils.js
    depends_on:
      - bg-parent1

  bg-child1-ui:
    image: beer-garden-ui:local
    container_name: bg-child1-ui
    stdin_open: true
    tty: true
    networks:
      - bg-network
    ports:
      - "8484:8484"
    volumes:
      - $PROJECT_HOME/beer-garden/src/ui:/home/brewmeister/beer-garden/ui
      - $PROJECT_HOME/dev-utils/beer-garden/conf/webpack.bg-child1.js:/home/brewmeister/beer-garden/ui/webpack.dev-utils.js
    depends_on:
      - bg-child1

  bg-child2-ui:
    image: beer-garden-ui:local
    container_name: bg-child2-ui
    stdin_open: true
    tty: true
    networks:
      - bg-network
    ports:
      - "8585:8585"
    volumes:
      - $PROJECT_HOME/beer-garden/src/ui:/home/brewmeister/beer-garden/ui
      - $PROJECT_HOME/dev-utils/beer-garden/conf/webpack.bg-child2.js:/home/brewmeister/beer-garden/ui/webpack.dev-utils.js
    depends_on:
      - bg-child2

  bg-parent1-ui-react:
    image: beer-garden-react:local
    container_name: bg-parent1-ui-react
    stdin_open: true
    tty: true
    environment:
      BEERGARDEN_HOST: bg-parent1
      BEERGARDEN_PORT: 2337
    networks:
      - bg-network
    ports:
      - "4000:4000"
    volumes:
      - $PROJECT_HOME/react-ui:/home/brewmeister/beer-garden/react-ui
    depends_on:
      - bg-parent1

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    networks:
      - bg-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: beer_garden
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - bg-network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq

  activemq:
    image: vromero/activemq-artemis:2.16-alpine-latest
    container_name: activemq
    restart: always
    environment:
      ARTEMIS_USERNAME: beer_garden
      ARTEMIS_PASSWORD: password
    networks:
      - bg-network
    ports:
      - "61613:61613"
      - "8161:8161"
    volumes:
      - $PROJECT_HOME/beer-garden/docker/docker-compose/data/activemq-config/etc-override-non-ssl:/var/lib/artemis/etc-override

networks:
  bg-network:
    driver: bridge
    name: bg-network

volumes:
  mongo-data:
  mongo-config:
  rabbitmq-home:
